services:
  app:
    image: node:18-alpine
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    environment:
      PORT: 8080
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Polit2019
      POSTGRES_DB: testdb
      POSTGRES_PORT: 5432
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Polit2019
      POSTGRES_DB: testdb
